nasa/ogma

ogma-cli/CHANGELOG.md, ogma-cli/src/CLI/CommandTop.hs, ogma-core/CHANGELOG.md, ogma-core/src/Command/CStructs2Copilot.hs, ogma-core/src/Command/CStructs2MsgHandlers.hs, ogma-core/src/Language/Trans/CStructs2Copilot.hs, ogma-core/templates/copilot-cfs/fsw/src/Properties.hs
Compliance with style requirements outlined in the description of #45.
=> Compliance with style requirements. Refs #45.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This PR updates the version numbers of all packages, as well as the version bounds of all dependencies on Copilot, as prescribed in the solution to #49.
=> Release 1.0.3. Refs #49.

ogma-cli/CHANGELOG.md, ogma-cli/src/CLI/CommandTop.hs, ogma-core/.hlint.yaml, ogma-core/CHANGELOG.md
This PR addresses all HLint suggestions in the code, as described in the solution proposed for #51.
=> Address hlint suggestions. Refs #51.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This PR updates the version numbers of all packages, as prescribed in the solution to #53.
=> Release 1.0.4. Refs #53.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This PR updates the version numbers of all packages, as prescribed in the solution to #60.
=> Release 1.0.5. Refs #60.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This PR updates the version numbers of all packages, as prescribed in the solution proposed for #64.
=> Release 1.0.6. Refs #64.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This PR updates the version numbers of all packages, as prescribed in the solution proposed for #69.
=> Release 1.0.7. Refs #69.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This PR updates the version numbers of all packages, as prescribed in the solution proposed for #81.
=> Release 1.0.8. Refs #81.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #98.
=> Release 1.0.10. Refs #98.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #103.
=> Release 1.0.11. Refs #103.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #112.
=> Release 1.1.0. Refs #112.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #117.
=> Release 1.2.0. Refs #117.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #145.
=>  Release 1.4.0. Refs #145.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Replace all homepages in cabal files to point to this repository, as prescribed in the solution proposed for #147.
=> Replace homepage. Refs #147.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #155.
=>  Release 1.4.1. Refs #155.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-language-xmlspec/CHANGELOG.md, ogma-language-xmlspec/ogma-language-xmlspec.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #208 .
=> Release 1.6.0. Refs #208.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Modify cFS backend to make more structured data directly available to the cFS template, as prescribed in the solution proposed for #229.
=> Make structured data available to cFS template. Refs #229.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-core/CHANGELOG.md, ogma-core/src/Command/ROSApp.hs, ogma-core/templates/ros/copilot/src/copilot_logger.cpp, ogma-core/templates/ros/copilot/src/copilot_monitor.cpp
Modify ROS backend to make more structured data directly available to the ROS template, as prescribed in the solution proposed for #244.
=> Make structured data available to ROS template. Refs #244.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-csv/CHANGELOG.md, ogma-language-csv/ogma-language-csv.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-lustre/CHANGELOG.md, ogma-language-lustre/ogma-language-lustre.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-language-xlsx/CHANGELOG.md, ogma-language-xlsx/ogma-language-xlsx.cabal, ogma-language-xmlspec/CHANGELOG.md, ogma-language-xmlspec/ogma-language-xmlspec.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #269  .
=> Release 1.7.0. Refs #269.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-cli/src/CLI/CommandOverview.hs, ogma-cli/src/CLI/CommandTop.hs, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/Overview.hs
Add overview command to `ogma-core` and expose in `ogma-cli`, as prescribed in the solution proposed for #272.
=> Add overview command. Refs #272.
