nasa/ogma

.travis.yml, ogma-cli/CHANGELOG.md
This PR includes a Travis script that builds Ogma, producing detailed logs, and running the rests. We pick GHC 8.8 as the version to build with, because it's not too modern or too old.
=> Enable CI on Travis with detailed logs. Refs #47.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-cs/src/Language/FRETComponentSpec/AST.hs, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal
Adapt the cabal files and the code to work with GHC 9.2, as prescribed in the solution proposed for #55.
=> Adapt Ogma to work with GHC 9.2. Refs #55.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/SMV2Copilot.hs, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/src/Language/FRETComponentSpec/AST.hs, ogma-language-smv/CHANGELOG.md, ogma-language-smv/grammar/SMV.cf
Support floating point numbers in SMV expressions, as prescribed in the solution proposed for #58.
=> Support floating point numbers in SMV expressions. Refs #58.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Updates all the licenses in the cabal files to `OtherLicense`, so that the packages can be accepted in hackage, as prescribed in the solution proposed for #62.
=> Update licenses in cabal files to `OtherLicense`. Refs #62.

ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Update `extra-source-files` in the cabal files of language libraries composed of auto-generated files only to include the `src` directory, so that the packages can be accepted in hackage, as prescribed in the solution proposed for #65 .
=> Add `src/.keep` files to `extra-source-files` in cabal files. Refs #65.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/CoCoSpec2Copilot.hs, ogma-core/src/Language/Trans/FRETComponentSpec2Copilot.hs, ogma-core/src/Language/Trans/FRETReqsDB2Copilot.hs, ogma-core/src/Language/Trans/SMV2Copilot.hs, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/grammar/CoCoSpec.cf, ogma-language-smv/CHANGELOG.md, ogma-language-smv/grammar/SMV.cf
Add the inequality operator in the grammars of SMV and CoCoSpec, and add the appropriate translation in `ogma-core`, as prescribed in the solution proposed for #71.
=> Support inequality operator in TL formulas in SMV and CoCoSpec. Refs #71.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-fret-cs/CHANGELOG.md, ogma-language-fret-cs/ogma-language-fret-cs.cabal, ogma-language-fret-reqs/CHANGELOG.md, ogma-language-fret-reqs/ogma-language-fret-reqs.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Mark packages as uncurated to prevent modifications to packages published on hackage, by people outside of the development team (e.g., Hackage maintainers), as prescribed in the solution proposed for #74.
=> Prevent modifications by people outside the project. Refs #74.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/ogma-cli.cabal, ogma-cli/src/CLI/CommandROSApp.hs
Replace all occurrences of ROS2 with ROS 2 in the code, package descriptions and documentation, as prescribed in the solution proposed for #83.
=> `ogma-cli`: Replace all occurrences of ROS2 with ROS 2. Refs #83.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/FRETReqsDB2Copilot.hs, ogma-core/src/Language/Trans/SMV2Copilot.hs, ogma-language-smv/CHANGELOG.md, ogma-language-smv/grammar/SMV.cf
Support MTL operators with number ranges in SMV parser, and add the necessary translation to `ogma-core`, as prescribed in the solution proposed for #101.
=> Support MTL operators with number ranges in SMV.

ogma-core/CHANGELOG.md, ogma-core/templates/copilot-cfs/fsw/for_build/Makefile, ogma-core/templates/copilot-cfs/fsw/mission_inc/copilot_cfs_perfids.h, ogma-core/templates/copilot-cfs/fsw/platform_inc/copilot_cfs_msgids.h, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs_events.h, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs_msg.h, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs_version.h
Remove trailing spaces from the cFS application template, as prescribed in the solution proposed for #108.
=> `ogma-core`: Remove trailing spaces from cFS app template. Refs #108.

ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs, ogma-core/templates/copilot-cfs/CMakeLists.txt, ogma-core/templates/copilot-cfs/fsw/mission_inc/copilot_cfs_perfids.h, ogma-core/templates/copilot-cfs/fsw/platform_inc/copilot_cfs_msgids.h, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs_version.h
Replace all mentions of the Sample App in the code and the template with mentions of the Copilot app, as prescribed in the solution proposed for #105.
=> `ogma-core`: Replace mentions of the Sample App. Refs #105.

ogma-cli/CHANGELOG.md, ogma-cli/README.md
Modify the installation instructions in README.md to include the cabal update step, as prescribed in the solution proposed for #100.
=> `ogma-cli`: Document cabal update step in README. Refs #100.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/Spec2Copilot.hs
Use the same name substitution when generating `trigger` calls in `Spec2Copilot`, as prescribed in the solution proposed for #120.
=> `ogma-core`: Fix missing stream name substitution. Refs #120.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/SMV2Copilot.hs
Replace the translation of the equivalence operator from SMV to be `(==)` in Copilot, as prescribed in the solution proposed for #126.
=> `ogma-core`: Fix translation of equivalence boolean operator from SMV. Refs #126.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/Spec2Copilot.hs
Sanitize handler names used in the generated Copilot specs, as prescribed in the solution proposed for #127.
=> `copilot-core`: Sanitize handler names. Refs #127.

ogma-core/CHANGELOG.md, ogma-core/src/Command/FPrimeApp.hs, ogma-core/src/Command/ROSApp.hs
Adjust the names of the expected handlers in the ROS and FPrime application generators to match what the Copilot backend is using, as prescribed in the solution proposed for #130.
=> `ogma-core`: Adjust handler names in ROS, FPrime app generators to match Copilot backend. Refs #130.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #133.
=> Release 1.3.0. Refs #133.

ogma-cli/CHANGELOG.md, ogma-cli/examples/ros-copilot/ROS.hs, ogma-cli/examples/ros-copilot/variables, ogma-cli/examples/ros-copilot/vars-db, ogma-core/CHANGELOG.md, ogma-core/src/Command/ROSApp.hs
Modify the ROS backend to map the input types `float` and `double` to the same types in the generated C++ ROS nodes, as prescribed in the solution proposed for #138.
=> `ogma-core`: Map `float` and `double` to the same types in C++. Refs #138.

.github/workflows/repo-ghc-8.6-cabal-2.4-ros.yml, .github/workflows/repo-ghc-8.6-cabal-2.4.yml, ogma-cli/CHANGELOG.md
Constrain the version of `aeson` to be greater than 2.0.2.0 in the CI jobs, as prescribed in the solution proposed for #151.
=> `ogma-cli`:  Constrain version of dependency in CI jobs. Refs #151.

ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/FRETComponentSpec2Copilot.hs, ogma-core/src/Command/FRETReqsDB2Copilot.hs
Replace uses of definitions from `IfElse` with other functions from `base`, as prescribed in the solution proposed for #150.
=> `ogma-core`: Remove dependency on `IfElse`. Refs #150.

ogma-core/CHANGELOG.md, ogma-core/templates/ros/Dockerfile
Fix incorrect path to `setup.bash` in latest Space ROS and fix Space ROS version to `humble-2024.10.0`, as prescribed in the solution proposed for #158.
=> `ogma-core`: Fix incorrect path when using Space ROS humble-2024.10.0. Refs #158.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/src/CLI/CommandCFSApp.hs, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/CFSApp.hs, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Adjust `ogma-cli` and `ogma-core` to allow customizing the cFS application by using custom-provided templates, as prescribed in the solution proposed for #157.
=> `ogma-cli`: Allow customizing the cFS application template. Refs #157.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/src/CLI/CommandROSApp.hs, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/CFSApp.hs, ogma-core/src/Command/ROSApp.hs, ogma-core/templates/ros/copilot/src/copilot_logger.cpp, ogma-core/templates/ros/copilot/src/copilot_monitor.cpp, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-extra/src/System/Directory/Extra.hs
Adjust `ogma-cli` and `ogma-core` to allow customizing the ROS application by using custom-provided templates, as prescribed in the solution proposed for #162.
=> `ogma-cli`: Allow customizing the ROS application template. Refs #162.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/Spec2Copilot.hs
Fix comment in generated Copilot spec, as prescribed in the solution proposed for #164.
=> `ogma-core`: Fix comment in generated Copilot spec. Refs #164.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/Spec2Copilot.hs
Modify Copilot spec generator to include a definition for `notPreviousNot`, as prescribed in the solution proposed for #168.
=> `ogma-core`: Add missing notPreviousNot to generated spec. Refs #168.

ogma-cli/CHANGELOG.md, ogma-cli/README.md
Update README to include a video of an Ogma-generated monitor running in ROS, demonstrated via Gazebo, as prescribed in the solution proposed for #172.
=> `ogma-cli`: Update README to demonstrate robotics. Refs #172.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/SMV2Copilot.hs
Rename module documentation to refer to SMV, as prescribed in the solution proposed for #176.
=> `ogma-core`: Correct name in documentation. Refs #176.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal
Add version bounds to base in all components in the cabal package description of `ogma-cli`, as prescribed in the solution proposed for #180.
=> `ogma-cli`: Add version bounds to `base`. Refs #180.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Update version numbers of all packages and adjust dependencies, as prescribed in the solution proposed for #178.
=> Release 1.5.0. Refs #178.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/src/CLI/CommandFPrimeApp.hs, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/FPrimeApp.hs, ogma-core/templates/fprime/Copilot.cpp, ogma-core/templates/fprime/Copilot.fpp, ogma-core/templates/fprime/Copilot.hpp, ogma-extra/CHANGELOG.md, ogma-extra/src/System/Directory/Extra.hs
Adjust `ogma-cli` and `ogma-core` to allow customizing the F' monitoring component by using custom-provided templates, as prescribed in the solution proposed for #185 .
=> `ogma-cli`: Allow customizing the F' component template. Refs #185.

ogma-cli/CHANGELOG.md, ogma-cli/src/CLI/CommandStandalone.hs, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/Standalone.hs, ogma-core/src/Language/Trans/Spec2Copilot.hs, ogma-core/templates/standalone/Copilot.hs, ogma-core/tests/Main.hs
Adjust `ogma-cli` and `ogma-core` to allow customizing the standalone Copilot monitoring application by using custom-provided templates, as prescribed in the solution proposed for #189.
Unlike in the solution proposed for #189, the README is not modified to explain how to use this feature, since there is no section in the current README explaining how the standalone command works.
=> `ogma-cli`: Allow customizing the standalone application template. Refs #189.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-copilot/CHANGELOG.md, ogma-language-copilot/ogma-language-copilot.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal, ogma-spec/CHANGELOG.md, ogma-spec/ogma-spec.cabal
Add information regarding where to file bug reports and where to find the source code to all cabal packages, as prescribed in the solution propose for #148.
=> Add repository information to cabal packages. Refs #148.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Add version bounds to all dependencies in the cabal packages, as prescribed in the solution proposed for #119 .
The version bounds are chosen so that Ogma can be installed with GHC 8.4.4, the lowest version supported based on the existing constraints on `base`, and GHC 9.4.8, the highest version supported (based on constraints to other packages, as well as the specifics of the current implementation).
=> Add version bounds to all dependencies in cabal packages. Refs #119.

ogma-cli/CHANGELOG.md, ogma-cli/src/CLI/CommandStandalone.hs, ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/FPrimeApp.hs, ogma-core/src/Command/ROSApp.hs, ogma-core/src/Command/Standalone.hs, ogma-core/tests/Main.hs, ogma-language-jsonspec/CHANGELOG.md, ogma-language-jsonspec/ogma-language-jsonspec.cabal, ogma-language-jsonspec/src/Language/JSONSpec/Parser.hs
Extend Ogma with the ability to preprocess properties by using a user-provided tool, as prescribed in the solution proposed for #197.
=> `ogma-cli`: Provide ability to preprocess properties via external command. Refs #197.

ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal, ogma-core/src/Command/Standalone.hs
Modify `ogma-core`'s standalone backend to treat the format name as a local file name when applicable, as prescribed in the solution proposed for #200.
=> `ogma-core`: Enable using user-provided file as format definition spec. Refs #200.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal, ogma-cli/tests/Main.hs, ogma-cli/tests/fcs-example1.json
This commit adds any examples needed by the tests to the `tests/` directory, adjust both the tests so that they can be located, and modifies the Cabal package to include all auxiliary test files in the Cabal source package, as prescribed in the solution proposed for #216.
=> `ogma-cli`: Add all auxiliary test files to distributable Cabal package. Refs #216.

ogma-core/CHANGELOG.md, ogma-core/src/Command/FPrimeApp.hs, ogma-core/src/Command/ROSApp.hs
Replace all imports of `liftIO` from `Control.Monad.Except` with imports from `Control.Monad.IO.Class` in both `ogma-core:Command.ROSApp` and `ogma-core:Command.FPrimeApp`, as prescribed in the solution proposed for #215.
=> `ogma-core`: Import `liftIO` from `Control.Monad.IO.Class`. Refs #215.

ogma-core/.hlint.yaml, ogma-core/CHANGELOG.md, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/grammar/SMV.cf, ogma-language-smv/ogma-language-smv.cabal
This commit removes old references to an earlier design of Ogma from both documentation and configuration files, as prescribed in the solution proposed for #220.
=> Remove references to old design of Ogma from config files, docs. Refs #220.

ogma-extra/CHANGELOG.md, ogma-extra/ogma-extra.cabal, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
This commit modifies version bounds of all libraries depending directly on Cabal to allow installation with Cabal 3.14, the most recent version of Cabal that does not require a change to the Haskell code, per the desired result and proposed solution in #213.
These changes enable Ogma to be used in Debian sid.
=> Bump version bounds of dependencies on Cabal. Refs #213. 

.github/workflows/repo-ghc-8.6-cabal-2.4-ros.yml, .github/workflows/repo-ghc-8.6-cabal-2.4.yml, cabal.project, ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-language-c/CHANGELOG.md, ogma-language-c/ogma-language-c.cabal, ogma-language-cocospec/CHANGELOG.md, ogma-language-cocospec/ogma-language-cocospec.cabal, ogma-language-smv/CHANGELOG.md, ogma-language-smv/ogma-language-smv.cabal
Specify dependencies on tools like `alex`, `happy` and `BNFC` using `build-tool-depends`, and update installation instructions accordingly, as prescribed in the solution proposed for #149.
=> Specify tool dependencies using `build-tool-depends`. Refs #149.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/CStructs2Copilot.hs
This commit updates the Copilot struct code generator to use the new function name `typeName` as `typename` has been removed, as prescribed in the solution proposed for #231.
=> `ogma-core`: Update Copilot struct code generator to use new function names. Refs #231.

ogma-core/CHANGELOG.md, ogma-core/src/Language/Trans/CStructs2Copilot.hs
Simplify the struct definitions generated by Ogma by leveraging generics, making data structs derive `Generic` and modifying type class methods to use the default versions of all methods, as prescribed in the solution proposed for #199.
=> `ogma-core`: Simplify Copilot struct definitions by using generics. Refs #199.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/src/CLI/CommandCFSApp.hs, ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs
Extend `cfs` command and the cFS backend to accept and use an optional JSON file containing additional variables to expand in the template, as prescribed in the solution proposed for #106.
=> Support passing additional template variables to the cFS backend. Refs #106.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs, ogma-core/templates/copilot-cfs/CMakeLists.txt, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.h
Remove all references to ICAROUS-specific data from the template and the cFS backend, and add new variables in places where we expect that users may need them, as prescribed in the solution proposed for #237.
=> Remove dependency on ICAROUS from generated cFS applications. Refs #237.

ogma-cli/CHANGELOG.md, ogma-cli/README.md
Modify the template variables in the F' section to use backticks so that they are properly formatted, as prescribed in the solution for #222.
=> `ogma-cli`: Fix formatting of template variables in README. Refs #222.

ogma-core/CHANGELOG.md, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Remove incorrect mention of an undefined function `split` from the cFS template, as prescribed in the solution proposed for #240 .
=> `ogma-core`: Remove incorrect function declaration from template. Refs #240.

ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs
Re-structure the cFS backend to make code sequential instead of nested by means of the `ExceptT` monad transformer, as prescribed in the solution proposed for #242.
=> `ogma-core`: Re-structure cFS backend to avoid nested conditions. Refs #242.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-core/CHANGELOG.md, ogma-core/src/Command/FPrimeApp.hs, ogma-core/templates/fprime/Copilot.cpp, ogma-core/templates/fprime/Copilot.fpp, ogma-core/templates/fprime/Copilot.hpp
Modify FPrime backend to make more structured data directly available to the FPrime template, as prescribed in the solution proposed for #246.
=> Make structured data available to FPrime template. Refs #246.

ogma-cli/CHANGELOG.md, ogma-cli/src/CLI/CommandCFSApp.hs, ogma-cli/src/CLI/CommandFPrimeApp.hs, ogma-cli/src/CLI/CommandROSApp.hs, ogma-cli/src/CLI/CommandStandalone.hs, ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs, ogma-core/src/Command/FPrimeApp.hs, ogma-core/src/Command/ROSApp.hs, ogma-core/src/Command/Standalone.hs, ogma-core/tests/Main.hs
Equalize the backends in terms of top-level names and interface, file handling, error handling, function naming, and production of results, and adjust the CLI and tests accordingly, as prescribed in the solution proposed for #248.
=> Equalize backends. Refs #248.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/src/CLI/CommandFPrimeApp.hs, ogma-cli/src/CLI/CommandROSApp.hs, ogma-cli/src/CLI/CommandStandalone.hs, ogma-core/CHANGELOG.md, ogma-core/src/Command/FPrimeApp.hs, ogma-core/src/Command/ROSApp.hs, ogma-core/src/Command/Standalone.hs, ogma-core/tests/Main.hs
Extend `ros`, `fprime` and `standalone` commands and the corresponding backends to accept and use an optional JSON file containing additional variables to expand in the template, as prescribed in the solution proposed for #250.
=> Support passing additional template variables to the ROS, FPrime, standalone backends. Refs #250.

ogma-cli/CHANGELOG.md, ogma-cli/README.md, ogma-cli/src/CLI/CommandCFSApp.hs, ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs
Extend the cFS backend to accept an additional argument filename containing an input specification, as well as arguments indicating the formats of the file and the properties, as well as a pre-processor, as prescribed in the solution proposed for #252.
=> `ogma-cli`: Make cFS backend accept spec as input. Refs #252.

ogma-core/CHANGELOG.md, ogma-core/ogma-core.cabal
Modify Cabal package to include all auxiliary test files in the Cabal source package, as prescribed in the solution proposed for #258.
=> `ogma-core`: Add all auxiliary test files to distributable Cabal package. Refs #258.

ogma-cli/CHANGELOG.md, ogma-cli/src/CLI/CommandCFSApp.hs, ogma-cli/src/CLI/CommandFPrimeApp.hs, ogma-cli/src/CLI/CommandROSApp.hs, ogma-cli/src/CLI/CommandStandalone.hs, ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs, ogma-core/src/Command/Common.hs, ogma-core/src/Command/FPrimeApp.hs, ogma-core/src/Command/ROSApp.hs, ogma-core/src/Command/Standalone.hs, ogma-core/tests/Main.hs
Extend both `ogma-core` and `ogma-cli` so that all code-generating backends accept as input expression to monitor an expression passed as argument, as prescribed in the solution proposed for #121.
=> `ogma-cli`: Extend code commands to accept expressions to monitor as CLI arguments. Refs #121.

ogma-cli/CHANGELOG.md, ogma-cli/ogma-cli.cabal
Bump upper version constraint on `optparse-applicative`, as prescribed in the solution proposed for #279.
=> `ogma-cli`: Bump upper version constraint on `optparse-applicative`. Refs #279.

ogma-core/CHANGELOG.md, ogma-core/templates/ros/Dockerfile
Modify the installation step for the generated ROS 2 packages in the Dockerfile that accompanies the ROS 2 template so that the packages are installed locally, as prescribed in the solution proposed for #288.
=> `ogma-core`: Install packages locally in ROS 2 dockerfile. Refs #288.

ogma-core/CHANGELOG.md, ogma-core/src/Command/CFSApp.hs, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Fix handling of message fields in cFS template when applicable, and adjust cFS backend to provide necessary information, as prescribed in the solution propose for #296.
=> `ogma-core`: Fix handling of message fields in cFS template. Refs #296.

ogma-core/CHANGELOG.md, ogma-core/templates/copilot-cfs/CMakeLists.txt
Modify `CMakeLists.txt` of cFS template to indicate dependencies between the commands executed, source files and generated files, as prescribed in the solution proposed for #299.
=> `ogma-core`: Avoid unnecessary recompilation of generated cFS app. Refs #299.

ogma-core/CHANGELOG.md, ogma-core/templates/copilot-cfs/fsw/platform_inc/copilot_cfs_msgids.h, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Remove all tabs from the cFS template code and indent modified lines based on surrounding code, as prescribed in the solution proposed for #294.
=> `ogma-core`: Remove tabs from cFS template code. Refs #294.

ogma-core/CHANGELOG.md, ogma-core/templates/copilot-cfs/CMakeLists.txt, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Modify cFS template to adjust `CMakeLists.txt` to list dependency on Copilot-generated C sources explicitly, and remove inclusion of Copilot monitor implementation directly into cFS application's main module, as prescribed in the solution proposed for #297.
=> `ogma-core`: Fix duplicate linkage of Copilot code in generated cFS app. Refs #297.

ogma-core/CHANGELOG.md, ogma-core/templates/copilot-cfs/fsw/src/Properties.hs, ogma-core/templates/copilot-cfs/fsw/src/copilot_cfs.c
Use alternate name for Copilot's main entry point in Copilot spec in cFS template, and adjust cFS application code accordingly, as prescribed in the solution proposed for #303.
=> `ogma-core`: Use alternate name for Copilot's step function in cFS template. Refs #303.
